const responseProcessors = {
  /**
   * request.url contains:
   * - HTTP request URL for HTTP listener
   * - topic/queue name for Kafka and AMQP listeners
   */
  sampleKafkaProcessor(request, response) {
    response.body = "this text is generated by processor";
  },

  sampleHttpProcessor(request, response) {
    response.headers["X-Request-Url"] = request.url;
  },
};

module.exports = responseProcessors;
