import { ChildProcess, spawn } from "child_process";
import fs from "fs";
import http from "http";
import net from "net";
import os from "os";
import path from "path";

const PROJECT_ROOT = path.join(__dirname, "..", "..");
const ENTRY_POINT = path.join(PROJECT_ROOT, "dist", "index.js");

export interface HttpResult {
  status: number;
  statusText: string;
  headers: http.IncomingHttpHeaders;
  body: string;
  elapsedMs: number;
}

export interface RequestOptions {
  method?: string;
  headers?: Record<string, string>;
  body?: string;
}

/**
 * Configuration written to config.jsonc. Ports are filled in by the harness.
 */
export interface MockServerConfig {
  listeners: {
    http?: Record<string, unknown>;
    [key: string]: unknown;
  };
}

/**
 * Black-box handle to a mock server running as a child process (`node dist/index.js`) over a temporary root
 * directory. The tests use only the public contract: HTTP ports, the config file and the responses directory.
 */
export class MockServerProcess {
  private output = "";
  private exitCode: number | null | undefined = undefined;

  private constructor(
    public readonly rootDir: string,
    public readonly httpPort: number,
    public readonly apiPort: number,
    private config: MockServerConfig,
    private child?: ChildProcess
  ) {}

  /**
   * Copies the fixture directory to a temporary root, writes the config and starts the server.
   */
  public static async start(config: MockServerConfig, fixtureDir: string): Promise<MockServerProcess> {
    const rootDir = fs.mkdtempSync(path.join(os.tmpdir(), "http-mock-server-"));
    copyDirectory(fixtureDir, rootDir);
    const [httpPort, apiPort] = await Promise.all([findFreePort(), findFreePort()]);
    const server = new MockServerProcess(rootDir, httpPort, apiPort, config);
    server.writeConfig(config);
    server.spawn();
    await server.waitUntilListening();
    return server;
  }

  /**
   * Rewrites config.jsonc; ports are preserved.
   */
  public writeConfig(config: MockServerConfig): void {
    this.config = config;
    const listeners = { ...config.listeners };
    if (listeners.http) {
      listeners.http = { ...listeners.http, port: this.httpPort };
    }
    const content = JSON.stringify({ apiPort: this.apiPort, listeners }, null, 2);
    fs.writeFileSync(path.join(this.rootDir, "config.jsonc"), "// generated by test harness\n" + content);
  }

  public getConfig(): MockServerConfig {
    return this.config;
  }

  public writeResponseFile(name: string, content: string): void {
    fs.writeFileSync(path.join(this.rootDir, "responses", name), content);
  }

  public get isRunning(): boolean {
    return this.exitCode === undefined;
  }

  public get log(): string {
    return this.output;
  }

  public http(urlPath: string, options?: RequestOptions): Promise<HttpResult> {
    return sendRequest(this.httpPort, urlPath, options);
  }

  public api(urlPath: string, options?: RequestOptions): Promise<HttpResult> {
    return sendRequest(this.apiPort, urlPath, options);
  }

  public async apiJson(urlPath: string): Promise<any> {
    const result = await this.api(urlPath);
    return result.body === "" ? undefined : JSON.parse(result.body);
  }

  public async stop(): Promise<void> {
    if (this.child && this.isRunning) {
      const exited = new Promise((resolve) => this.child?.once("exit", resolve));
      this.child.kill();
      await exited;
    }
    fs.rmSync(this.rootDir, { recursive: true, force: true });
  }

  private spawn(): void {
    this.child = spawn(process.execPath, [ENTRY_POINT], {
      cwd: this.rootDir,
      env: { ...process.env, HTTP_MOCK_SERVER_ROOT: this.rootDir },
      stdio: ["ignore", "pipe", "pipe"],
    });
    this.child.stdout?.on("data", (chunk) => (this.output += chunk));
    this.child.stderr?.on("data", (chunk) => (this.output += chunk));
    this.child.on("exit", (code) => (this.exitCode = code));
  }

  private async waitUntilListening(): Promise<void> {
    const deadline = Date.now() + 10_000;
    const ports = this.config.listeners.http && this.config.listeners.http.enabled !== false ? [this.apiPort, this.httpPort] : [this.apiPort];
    for (const port of ports) {
      while (!(await isPortOpen(port))) {
        if (!this.isRunning) {
          throw new Error(`Mock server exited with code ${this.exitCode}:\n${this.output}`);
        }
        if (Date.now() > deadline) {
          throw new Error(`Mock server did not start listening on port ${port}:\n${this.output}`);
        }
        await new Promise((resolve) => setTimeout(resolve, 50));
      }
    }
  }
}

export function sendRequest(port: number, urlPath: string, options: RequestOptions = {}): Promise<HttpResult> {
  const start = Date.now();
  return new Promise((resolve, reject) => {
    const request = http.request({ host: "127.0.0.1", port, path: urlPath, method: options.method || "GET", headers: options.headers }, (response) => {
      let body = "";
      response.setEncoding("utf-8");
      response.on("data", (chunk) => (body += chunk));
      response.on("end", () =>
        resolve({
          status: response.statusCode || 0,
          statusText: response.statusMessage || "",
          headers: response.headers,
          body,
          elapsedMs: Date.now() - start,
        })
      );
    });
    request.on("error", reject);
    request.end(options.body);
  });
}

function findFreePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const server = net.createServer();
    server.on("error", reject);
    server.listen(0, "127.0.0.1", () => {
      const address = server.address() as net.AddressInfo;
      server.close(() => resolve(address.port));
    });
  });
}

function isPortOpen(port: number): Promise<boolean> {
  return new Promise((resolve) => {
    const socket = net.connect(port, "127.0.0.1");
    socket.once("connect", () => {
      socket.destroy();
      resolve(true);
    });
    socket.once("error", () => resolve(false));
  });
}

function copyDirectory(source: string, target: string): void {
  fs.mkdirSync(target, { recursive: true });
  for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
    const sourcePath = path.join(source, entry.name);
    const targetPath = path.join(target, entry.name);
    if (entry.isDirectory()) {
      copyDirectory(sourcePath, targetPath);
    } else {
      fs.copyFileSync(sourcePath, targetPath);
    }
  }
}
